/* vxwm compile-time options */

/* KILLER FEATURES */
#define INFINITE_TAGS 1
#define IT_SHOW_COORDINATES_IN_BAR 1
#define ZOOM 0

/* Move/Resize */
#define BETTER_RESIZE 1
#define BR_CHANGE_CURSOR 1
#define LOCK_MOVE_RESIZE_REFRESH_RATE 1
#define USE_RESIZECLIENT_FUNC 0
#define RESIZING_WINDOWS_IN_ALL_LAYOUTS_FLOATS_THEM 1
#define MOVE_RESIZE_WITH_KEYBOARD 1

/* Kind of eye candy */
#define GAPS 1
#define XRDB 0

/* Tagging */
#define TAG_TO_TAG 1
#define SLOWER_TAGS_ANIMATION 0
#define WINDOWMAP 1
#define PDWM_LIKE_TAGS_ANIMATION 0

/* Bar */
/* Internal */
#define ALT_CENTER_OF_BAR_COLOR 1
#define BAR_HEIGHT 1
#define BAR_PADDING 1
#define OCCUPIED_TAGS_DECORATION 0

/* External */
#define EXTERNAL_BARS 1
#define EWMH_TAGS 1

/* Warp to client */
#define WARP_TO_CLIENT 0
#define WARP_TO_CENTER_OF_NEW_WINDOW 0
#define WARP_TO_CENTER_OF_PREVIOUS_WINDOW 0
#define WARP_TO_CENTER_OF_SWAPMASTERED_WINDOW 0
#define WARP_TO_CENTER_OF_WINDOW_AFFECTED_BY_INCNMASTER 0
#define WARP_TO_CENTER_OF_WINDOW_AFFECTED_BY_ENHANCED_TOGGLE_FLOATING 0
#define WARP_TO_CENTER_OF_WINDOW_AFFECTED_BY_FOCUSSTACK 0
#define WARP_TO_CENTER_OF_WINDOW_MOVED_BY_KEYBOARD 0

/* Misc */
#define AUTOSTART 1
#define FULLSCREEN 1
#define MOVE_IN_TILED 1
#define DIRECTIONAL_FOCUS 1
#define DIRECTIONAL_MOVE 1

/* Floating */
#define FLOATING_LAYOUT_FLOATS_WINDOWS 1
#define ENHANCED_TOGGLE_FLOATING 1
#define RESTORE_SIZE_AND_POS_ETF 1
